[build]
command = "npm run build"
publish = "dist/your-app-name"

[functions]
directory = "netlify/functions"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
